version: '3'
services:
  node-app:
    build:
      context: ./backend  # Chemin vers le répertoire contenant ton Dockerfile Node.js
    ports:
      - "3000:3000"  # Mappe le port 3000 du conteneur au port 3000 de ta machine
    volumes:
      - ./backend:/app  # Monte ton répertoire local à /app dans le conteneur
    environment:
      - NODE_ENV=development

  nginx:
    build:
      context: ./frontend # Chemin vers le répertoire contenant ton Dockerfile Nginx
    ports:
      - "8082:80"  # Mappe le port 80 du conteneur au port 80 de ta machine
    volumes:
      - ./frontend:/usr/share/nginx/html
