version: '3'
services:
  node-app:
    env_file:
      - .env
    build:
      context: ./backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
    environment:
      - NODE_ENV=development

  nginx:
    build:
      context: ./frontend
    ports:
      - "8082:80"
      - "8443:443"  # Port HTTPS expose
    volumes:
      - ./frontend:/usr/share/nginx/html
      - ./frontend/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./frontend/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certs:/etc/nginx/certs:ro  # ✅ Montage du dossier des certificats
    depends_on:
      - node-app
