# Utilise l'image officielle de Node.js
FROM node:16

# Définit le répertoire de travail
WORKDIR /app

# Copie les fichiers package.json et package-lock.json
COPY package.json package-lock.json ./

# Installe les dépendances
RUN npm install

# Copie l
